import { SimTime, SimulationClock } from './clock.js';
import { SimulationEvent } from './events.js';
import { BeadStore } from '../core/bead-store.js';
import { PersonaRegistry } from '../core/persona-registry.js';
import type { PersonaWithState } from '../core/persona.js';
import type { Bead, BeadCreate } from '../core/bead.js';

export interface AdvanceResult {
  newTime: SimTime;
  events: SimulationEvent[];
  completedBeads: string[]; // bead IDs
  newBeads: string[]; // new bead IDs
  chatMessages: Array<{ persona: string; message: string }>;
}

// Chat messages generated by personas during idle time
const IDLE_MESSAGES = [
  'Anyone looked at the failing CI pipeline?',
  'I pushed a small refactor — let me know if it causes issues.',
  'Heads up, I am rebasing the feature branch.',
  'The docs for this module are out of date, I will update them.',
  'Just filed a ticket for the flaky test.',
  'Quick question — should we use the new API or the legacy one here?',
  'Good morning team, picking up where I left off yesterday.',
  'I noticed some tech debt in the auth module. Worth tracking?',
  'Sprint retro notes are in the wiki if anyone wants to review.',
  'Deploy went smoothly, no rollback needed.',
];

// Templates for new beads that Priya-archetype personas might create
const NEW_BEAD_TEMPLATES = [
  { title: 'Add unit tests for recent changes', type: 'test' as const },
  { title: 'Update API documentation', type: 'docs' as const },
  { title: 'Refactor error handling', type: 'refactor' as const },
  { title: 'Fix edge case in input validation', type: 'bugfix' as const },
  { title: 'Improve logging coverage', type: 'infra' as const },
  { title: 'Add integration test for new endpoint', type: 'test' as const },
  { title: 'Clean up deprecated code paths', type: 'refactor' as const },
];

/**
 * Advance the simulation clock and resolve persona activity.
 *
 * For each persona with an in_progress bead:
 *   - Calculate completion probability based on elapsed time
 *   - Roll for completion (simple random)
 *   - If completed: update bead status to 'done', generate event
 *
 * May generate 1-2 new beads (from Priya-archetype / gatekeeper / architect personas).
 * Generates 1-3 chat messages from active personas.
 * Checks for sprint boundaries.
 */
export class AdvanceEngine {
  constructor(
    private clock: SimulationClock,
    private beadStore: BeadStore,
    private personas: PersonaRegistry,
  ) {}

  async advance(days: number): Promise<AdvanceResult> {
    // No-op when days is 0 or not provided
    if (days <= 0) {
      return {
        newTime: this.clock.current,
        events: [],
        completedBeads: [],
        newBeads: [],
        chatMessages: [],
      };
    }

    const previousTime = this.clock.current;
    const events: SimulationEvent[] = [];
    const completedBeads: string[] = [];
    const newBeads: string[] = [];
    const chatMessages: Array<{ persona: string; message: string }> = [];

    // Advance the clock
    const newTime = this.clock.advanceDays(days);

    const elapsedDays = newTime.logical_day - previousTime.logical_day;

    // --- Process persona bead progress ---
    const allPersonas = this.personas.listAll();
    for (const persona of allPersonas) {
      if (!persona.state.currentBead) continue;

      const bead = this.beadStore.getById(persona.state.currentBead);
      if (!bead || bead.status === 'done') continue;

      const completed = this.rollForCompletion(bead, persona, elapsedDays);
      if (completed) {
        await this.completeBead(bead, persona, newTime, events);
        completedBeads.push(bead.id);
      } else {
        // Persona is still working — maybe emit a progress event
        events.push({
          type: 'branch_updated',
          persona: persona.definition.slug,
          bead_id: bead.id,
          description: `${persona.definition.name} pushed changes to ${bead.branch ?? 'their branch'}`,
          sim_time: { day: newTime.logical_day, hour: newTime.hour },
        });
      }
    }

    // --- Maybe generate new beads ---
    const creators = allPersonas.filter((p) =>
      ['gatekeeper', 'architect', 'mentor'].includes(p.definition.archetype),
    );
    if (creators.length > 0 && Math.random() < 0.4) {
      const creator = creators[Math.floor(Math.random() * creators.length)];
      const newBead = await this.generateNewBead(creator, newTime, events);
      if (newBead) {
        newBeads.push(newBead);
      }
    }

    // --- Generate chat messages ---
    const activePersonas = this.personas.getAllActive();
    const messageCount = Math.min(
      activePersonas.length,
      1 + Math.floor(Math.random() * 3),
    );
    const shuffled = activePersonas.sort(() => Math.random() - 0.5);
    for (let i = 0; i < messageCount; i++) {
      const persona = shuffled[i];
      const message =
        IDLE_MESSAGES[Math.floor(Math.random() * IDLE_MESSAGES.length)];
      chatMessages.push({
        persona: persona.definition.name,
        message,
      });
      events.push({
        type: 'chat_message',
        persona: persona.definition.slug,
        description: `${persona.definition.name}: ${message}`,
        sim_time: { day: newTime.logical_day, hour: newTime.hour },
      });
    }

    // --- Check for sprint boundary ---
    if (previousTime.sprint !== newTime.sprint) {
      events.push({
        type: 'sprint_boundary',
        description: `Sprint ${previousTime.sprint} ended. Sprint ${newTime.sprint} begins.`,
        sim_time: { day: newTime.logical_day, hour: newTime.hour },
      });
    }

    // Persist any dirty persona state to disk
    await this.personas.save();

    return { newTime, events, completedBeads, newBeads, chatMessages };
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /**
   * Roll for bead completion. Probability increases with elapsed time and
   * persona seniority. A 1-day bead has ~40% base chance per day, scaling
   * up so most beads complete within 2-3 days.
   */
  private rollForCompletion(
    _bead: Bead,
    persona: PersonaWithState,
    elapsedDays: number,
  ): boolean {
    const seniorityBonus: Record<string, number> = {
      junior: 0.0,
      mid: 0.05,
      senior: 0.10,
      staff: 0.15,
      principal: 0.20,
    };

    const baseRate = 0.4;
    const bonus = seniorityBonus[persona.definition.seniority] ?? 0;
    // Each elapsed day gives an independent chance, compounded
    const probNotDone = Math.pow(1 - (baseRate + bonus), elapsedDays);
    const probDone = 1 - probNotDone;

    return Math.random() < probDone;
  }

  /** Mark a bead as done and update persona state. */
  private async completeBead(
    bead: Bead,
    persona: PersonaWithState,
    time: SimTime,
    events: SimulationEvent[],
  ): Promise<void> {
    await this.beadStore.updateStatus(bead.id, 'done');
    await this.personas.updateState(persona.definition.slug, {
      currentBead: null,
      currentBranch: null,
      beadsCompleted: [...persona.state.beadsCompleted, bead.id],
      lastActiveAt: new Date().toISOString(),
    });

    events.push({
      type: 'bead_completed',
      persona: persona.definition.slug,
      bead_id: bead.id,
      description: `${persona.definition.name} completed "${bead.title}"`,
      sim_time: { day: time.logical_day, hour: time.hour },
    });
  }

  /** Maybe create a new bead from a creator-archetype persona. */
  private async generateNewBead(
    creator: PersonaWithState,
    time: SimTime,
    events: SimulationEvent[],
  ): Promise<string | null> {
    const template =
      NEW_BEAD_TEMPLATES[Math.floor(Math.random() * NEW_BEAD_TEMPLATES.length)];

    const input: BeadCreate = {
      title: template.title,
      description: `Filed by ${creator.definition.name} during sprint ${time.sprint}.`,
      team: creator.definition.team,
      priority: 'medium',
      status: 'open',
      assigned_to: null,
      depends_on: [],
      acceptance_criteria: ['Implementation meets team standards'],
      skill_targets: [],
      type: template.type,
    };

    const bead = await this.beadStore.create(input);

    events.push({
      type: 'bead_created',
      persona: creator.definition.slug,
      bead_id: bead.id,
      description: `${creator.definition.name} created bead "${template.title}"`,
      sim_time: { day: time.logical_day, hour: time.hour },
    });

    return bead.id;
  }
}
